# .goreleaser.yml
# Build customization
project_name: kubereplay

#before:
#  hooks:
#   - go test ./pkg/...
#   - go fmt
#   - go vet

builds:
  - binary: kubereplay-controller
    main: ./cmd/controller-manager/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
       - 6
       - 7
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
  - binary: kubereplay-initializer
    main: ./cmd/initializer-controller/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
       - 6
       - 7
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
release:
  github:
    owner: lwolf
    name: kubereplay
  prerelease: true

dockers:
  - image: quay.io/lwolf/kubereplay-controller-amd64
    dockerfile: Dockerfile.controller
    binary: kubereplay-controller
    goos: linux
    goarch: amd64
    tag_templates:
    - "{{ .Tag }}"
  - image: quay.io/lwolf/kubereplay-initializer-amd64
    dockerfile: Dockerfile.initializer
    binary: kubereplay-initializer
    goos: linux
    goarch: amd64
    tag_templates:
    - "{{ .Tag }}"
  - image: quay.io/lwolf/kubereplay-controller-arm64
    dockerfile: Dockerfile.controller
    binary: kubereplay-controller
    goos: linux
    goarch: arm64
    tag_templates:
    - "{{ .Tag }}"
  - image: quay.io/lwolf/kubereplay-initializer-arm64
    dockerfile: Dockerfile.initializer
    binary: kubereplay-initializer
    goos: linux
    goarch: arm64
    tag_templates:
    - "{{ .Tag }}"

git:
  short_hash: true
