# .travis.yml
language: go

# needed for the docker pipe
services:
- docker

before_install:
  - docker login -u ${QUAY_LOGIN} -p ${QUAY_PASSWORD} quay.io

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
